// <auto-generated />
namespace jrt.jcgl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Alert_ProdutionPlanMain_RawMaterialRequirement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alert_ProdutionPlanMain_RawMaterialRequirement));
        
        string IMigrationMetadata.Id
        {
            get { return "201611191310437_Alert_ProdutionPlanMain_RawMaterialRequirement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
