// <auto-generated />
namespace jrt.jcgl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Alert_OrganizationUnit_OrganizationUnitId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alert_OrganizationUnit_OrganizationUnitId));
        
        string IMigrationMetadata.Id
        {
            get { return "201611071344017_Alert_OrganizationUnit_OrganizationUnitId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
